---
output:
  pdf_document:
    toc: no
    #toc_depth: '3'
  html_document:
    code_folding: hide
    fig_caption: yes
    number_sections: no
    theme: readable
    toc: no
    #toc_depth: 3
    #toc_float: yes
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir=here::here())
knitr::opts_chunk$set(warning=F, message=F, echo=F, results=F,fig.width=6, fig.height=5)
options(tinytex.verbose = TRUE)
library(here)
```


# Proposal for a 3-parameter double logistic selectivity form

In an attempt to provide enough flexibility as warranted based on the catch-at-age
patterns observed for this stock, we developed a differentiable 3-parameter "double logistic"
selectivity pattern. 


$s_{t,a} =  \left[ {1+e^{\frac{-ln(19)(a-\gamma_1)}{p_1} }} \right]^{-1} \left[  1-\left( {1+e^{\frac{-ln(19)(a-\gamma_2)}{p_3} }} \right)^{-1} \right]0.95^{-2}$

with

$\gamma_1 = p_1 + p_2$

$\gamma_2 = p_1 + \gamma_1 + p_3$

and

$\gamma_1=$   first (ascending) inflection point of the selectivity function; 

$\gamma_2=$   second (descending) inflection point of the selectivity function;

$p_1=$ distance between first inflection point and age at 95% selection;

$p_2=$ parameter to be used with p1 to get first inflection point of the selectivity function; and

$p_3=$ second slope of the selectivity function.

The selectivity function ADMB snippets are as presented below:


```
  sel_p1_fsh(k)  = exp(logsel_p1_fsh(k));
  sel_p2_fsh(k)  = exp(logsel_p2_fsh(k));
  sel_p3_fsh(k)  = exp(logsel_p3_fsh(k));
...
          bu = sel_p1_fsh(k,isel_ch_tmp);
          du = sel_p2_fsh(k,isel_ch_tmp);
          dd = sel_p3_fsh(k,isel_ch_tmp);
			    bd = bu + du + dd;
...
// applied to a vector constant at end is log(0.95*0.95)
  log_sel_fsh(k,i)(1,nselages_fsh(k)) = 
    -log(1.0 + exp(-2.9444389792/du * 
    ( age_vector(1,nselages_fsh(k)) - bu) )) +
               log(1. - 1./(1.0 + exp(-2.9444389792/dd * 
               ( age_vector(1,nselages_fsh(k)) - bd))) )  + 0.102586589 ; 

```
