# Analytic approach

```{r setupx, include=FALSE}
thisyr<-2023
lastyr<-2022
```
## General model structure

A statistical age-structured assessment model conceptually outlined in
Fournier and Archibald (1982) and like Methot's (1990) stock synthesis
model was applied over the period 1964--`r thisyr`. A technical
description is presented in the "EBS Pollock Model Description"
appendix. The analysis was first introduced in the 1996 SAFE report and
compared to the cohort analyses that had been used previously and was
later documented in Ianelli and Fournier (1998). The model was written
in ADMB---a library for non-linear estimation and statistical
applications (Fournier et al. 2012). The data updated from last year's
analyses include:

-   The `r thisyr-1` fishery age composition data were added 

-   The catch biomass estimates were updated through to the current year

-   The `r thisyr` bottom-trawl survey index, weight, and age composition data were 
     revised and added 

-   The `r thisyr` acoustic-trawl survey index, weight, and preliminary age 
     composition data were  added 

-   The AVO backscatter data collected opportunistically from the 2022
    bottom trawl survey and post processed into the AVO backscatter
    index were included.

A simplified version of the assessment (with mainly the same data and
likelihood-fitting method) is included as a supplemental multi-species
assessment model. As presented since 2016, it allows for trophic
interactions among key prey and predator species and for pollock, and it
can be used to evaluate age and time-varying natural mortality estimates
in addition to alternative catch scenarios and management targets (see
this volume: [EBS multi-species
model](https://apps-afsc.fisheries.noaa.gov/Plan_Team/2022/EBSmultispp.pdf)).

## Description of alternative models

In the 2019 assessment, the spatio-temporal model fit to BTS CPUE data
*including stations from the NBS* was expanded using the VAST methods
detailed in Thorson (2018). This data treatment was included as a model
alternative and adopted for ABC/OFL specifications by the SSC in 2020
along with other modifications including a spatio-temporal treatment of
the age composition data. This year, we used the same model
configuration and simply examined the influence of additional data that
became available this year. For projections we added the ability to test
alternative Tier scenarios. The current base model is Model 20.0a, which
was adopted last year by the SSC, and which differed from the previous
base model (Model 16.2) in that it included the 2020 USV acoustic
biomass estimate as an extension of the standard AT survey biomass time
series and excluded the 1978 year class from the estimation of the
stock-recruitment relationship. We examined the following alternative models:

```{=tex}
\begin{description}

\item[20.0]The model selected last year which omitted the 1978 year-class from affecting the SRR (referred to as "Base")

\item[20.1]As 20.0 but estimating $M$ with a prior distribution (referred to as "Est. M")

\item[20.2]As 20.0 but updating the Francis weights (referred to as "Wt Comp").

\end{description}
```
In an effort to test different stock assessment software, we adopted the
pollock data and used some of the model software that was simulation
tested in Li et al. (2021). While preliminary, the results were
consistent with the bespoke model used here. However, the impact of
missing features in the more generalized models tested in this paper
requires more investigation. Specifically, the bespoke model used here
includes an informed fixed-effects model for projecting weight-at-age
and uses a covariance matrix for index time series that is unavailable
in the models tested in Li et al. (2021).

<!-- ### Tier 1 considerations

In the 2020 assessment we examined the factors affecting Tier 1
classifications including the required "reliability" of the estimated
pdf of $F_{MSY}$, i.e., the influence of assumptions related to the
uncertainties on the stock recruitment relationship, body mass-at-age,
maturation, and fishery selectivity. For a number of years the Tier 1
ABC and OFL specifications for EBS pollock have been very high, in
excess of the 2 million t OY for combined groundfish stocks managed
within this FMP area. This has been because the spawning stock estimates
have been well above target and mean levels. To add precaution to these
estimates, ABC recommendations have been below the maximum permissible
under Tier 1 but the rationale for such an adjustment could be improved.
As such, the SSC requested an examination of the issues related to
classifying this stock in Tier 1 versus Tier 3. The FMP (under amendment
56) guides this classification. It notes that a reliable estimate of
$F_{MSY}$ and its uncertainty (as expressed through a probability
distribution or PDF) is required. Since these values depend primarily on
the stock-recruitment relationship (SRR), the following sensitivities
were pursued relative to the status quo (Model 20) configuration:

-   As status quo (i.e., ignoring the influence of the 1978 year class
    on the SRR).

-   As in sensitivity a) but with a less informative prior on steepness

-   As in status quo but the SRR conditioned such that
    $F_{MSY}=F_{35\%}$

-   As in status quo but the SRR conditioned such that
    $F_{MSY}=F_{45\%}$

The first option was intended to reflect that the high value observed of
the 1978 year-class occurred under an estimated low level of spawning
biomass (designated Model 20.0a). The rationale for excluding this
influential value was that the stock structure and environmental
conditions may differ now, indicating non-stationarity in the
relationship. Results showed that it mattered but was relatively minor
and seemed unlikely to disqualify the estimates required for Tier 1.
Sensitivity test b) was intended to illustrate the role of the prior
mean and variance on the steepness estimate. Finally sensitivities c)
and d) were considered as how the SRR may translate an implicit
assumption under Tier 3 since $F_{35\%}$ is a proxy for $F_{MSY}$ and
$F_{45\%}$ is closer to the recent mean SPR rate.
 -->
### Input sample size

Sample sizes for age-composition data were re-evaluated in 2016 against
the trade-off with flexibility in time and age varying selectivity. In subsequent
assessment years the values have changed significantly from the 4-periods
of fishery data from which these weights were applied and calculated.
Principally, this work resulted in tuning the recent era (1991-present year) to an
average sample sizes of 350 for the fishery and then using estimated values for the
period 1978-1990 and as earlier (Table \ref{tab:input_n}). We assumed
average values of 100 and 50 for the BTS and ATS data, respectively with
inter-annual variability reflecting the variability in the number of
hauls sampled for ages. This year we re-evaluated one-step tuning 
as a sensitivity following Francis 2011 (equation TA1.8, hereafter referred to as Francis weights).

Recent work has shown ways to improve estimation schemes that deal with the interaction
between flexibility in fishery selectivity and statistical properties of 
composition data sample size. 
Specifically, the Dirichlet-multinomial using either Laplace approximation (Thorson et al., 2015) or adnuts (Monnahan and
Kristensen, 2018) should be implemented (e.g., as shown by Xu et al., 2020). We hope to evaluate these 
and alternatives in the coming year.

## Parameters estimated outside of the assessment model

### Natural mortality and maturity at age

The baseline model specification has been to use constant natural
mortality rates at age (M=0.9, 0.45, and 0.3 for ages 1, 2, and 3+
respectively (Wespestad and Terry 1984). When predation was explicitly
considered estimates tended to be higher and more variable (Holsman et al.
*this volume*; Holsman et al. 2015; Livingston and Methot 1998; Hollowed
et al. 2000). Clark (1999) found that specifying a conservative (lower)
natural mortality rate may be advisable when natural mortality rates are
uncertain. More recent studies confirm this (e.g., Johnson et al. 2015).

In the supplemental multi-species assessment model alternative values of
age and time-varying natural mortality are presented. As in past years
the estimates indicate higher values than used here. In the 2018
assessment we evaluated natural mortality, and it was noted that the
survey age compositions favored lower values of *M* while the fishery
age composition favored higher values. This is consistent with the
patterns seen in the BTS survey data as they show increased abundances
of "fully selected" cohorts. Hence, given the model specification
(asymptotic selectivity for the BTS age composition data), lower natural
mortality rates would be consistent with those data. Given these
trade-offs, structural model assumptions were held to be the same as
previous years for consistency (i.e., the mortality schedule presented
below).

Maturity-at-age values used for the EBS pollock assessment were
originally based on Smith (1981) and were later reevaluated (e.g., Stahl
2004; Stahl and Kruse 2008a; and Ianelli et al. 2005). These studies
found inter-annual variability but general consistency with the original
schedule of proportion mature at age.

Based on results from a distinct (apparently) but adjacent stock (Bogoslof assessment, this
volume) where fishing 
has been curtailed since 1992 and spawning surveys have taken place with regularity
since then (and included age data) we evaluate as a sensitivity estimated natural mortality for
pollock age 3-yrs and older. For the "base" model (model 2020) we continue to use
assumed natural mortality-at-age and maturity-at-age (for all models; Smith 1981) as in
previous assessments:

```{=tex}
\begin{table}[ht]
\centering
\label{tab:dataextent}
\scalebox{0.9}{
\begin{tabular}{rrrrrrrrrrrrrrrr}
\hline
Age&1&2&3&4&5&6&7&8&9&10&11&12&13&14&15 \\
\hline
$M$&0.90&0.45&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30&0.30 \\
$P_{mat}$&0.00&0.008&0.29&0.64&0.84&0.90&0.95&0.96&0.97&1.00&1.00&1.00&1.00&1.00&1.00 \\
\hline
\end{tabular}
}
\end{table}
```
### Length and weight-at-age

Age determination methods have been validated for pollock (Kimura et al.
1992; Kimura et al. 2006, and Kastelle and Kimura 2006). EBS pollock
size-at-age show important differences in growth with differences by
area, year, and year class. Pollock in the northwest area are typically
smaller at age than pollock in the southeast area. The differences in
average weight-at-age are taken into account by stratifying estimates of
catch-at-age by year, area, season, and weighting estimates proportional
to catch.

The assessment model for EBS pollock accounts for numbers of individuals
in the population. As noted above, management recommendations are based
on allowable catch levels expressed as tons of fish. While estimates of
pollock catch-at-age are based on large data sets, the data are only
available up until the most recent completed calendar year of fishing
(e.g., 2021 for this year). Consequently, estimates of weight-at-age in
the current year are required to map total catch biomass (typically
equal to the quota) to numbers of fish caught (in the current year).
Therefore, if there are errors (or poorly accounted uncertainty) in the
current and future mean weight-at-age, this can translate directly into
errors between the expected fishing mortality and what mortality occurs.
For example, if the mean weight-at-age is biased high, then an ABC (and
OFL) value will result in greater numbers of fish being caught (and
fishing mortality being higher due to more fish fitting within the ABC).

As in previous assessments, we explored patterns in size-at-age and fish
condition. Using the NMFS fishery observer data on weight given length
we:

1.  extracted all data where non-zero measurements of pollock length and
    weight were available between the lengths of 35 and 60 cm for the
    EBS region

2.  computed the mean value of body mass (weight) for each cm length bin
    over all areas and time

3.  divided each weight measurement by that mean cm-specific value (the
    "standardization" step)

4.  plotted these standardized values by different areas, years, months
    etc. to evaluate condition differences (pooling over ages is
    effective as there were no size-specific biases apparent)

In the first instance, the overarching seasonal pattern in body mass
relative to the mean shows that as the winter progresses prior to peak
spawning, pollock are generally skinnier than average whereas in July,
the median is about average (Fig. \ref{fig:fsh_lw_month}). As the
summer/fall progresses, fish were at their heaviest given length (Fig.
\ref{fig:fsh_lw_month}). This is also apparent when the data are
aggregated by A- and B-seasons (and by east and west of 170$^\circ$W;
referred to as SE and NW respectively) when plotted over time (Fig.
\ref{fig:fsh_lw_anom_str_yr_box}, where stratum 1 = A season, stratum 2
= B season SE, and stratum 3 = B season NW). 
Combining across seasons, the fishery data shows that recent years were below
average weight given length (Fig. \ref{fig:fsh_lw_anom_yr_box}; note
that the anomalies are based on the period 1991-2022).

Examining the weight-at-age, there are also patterns of variability that
vary due to environmental conditions in addition to spatial and temporal
patterns of the fishery. Based on the bootstrap distributions and large
sample sizes, the within-year sampling variability for pollock is small.
However, the between-year variability in mean weights-at-age is
relatively high (Table \ref{tab:wtage}). The coefficients of variation
between years are on the order of 6% to 9% (for the ages that are
targeted) whereas the sampling variability is generally around 1% or 2%.
The approach to account for the identified mean weight-at-age having
clear year and cohort effects was continued (e.g., Fig.
\ref{fig:fsh_wtage_comb}). Details were provided in appendix 1A of
Ianelli et al. (2016). The results from this method showed the relative
variability between years and cohorts and provide estimates for
`r paste0(thisyr,"--",thisyr+2)` (Table \ref{tab:wtage}). How these
fishery weights-at-age estimates can be supplemented using survey
weights-at-age is further illustrated in Fig.
\ref{fig:fish_wtage_data_pred}.

In the 2020 and 2021 fishery, the average weight-at-age for ages 6-8 (the
2012-2014 year classes) was below the time series average. These cohorts
have fluctuated around their means in recent years (Fig.
\ref{fig:fsh_wtage_comb}). To examine this more closely, we split the
bootstrap results into area-season strata and were able to get an
overall picture of the pattern by strata (Fig.
\ref{fig:fsh_wtage_strata} and Fig. \ref{fig:fsh_wtage_strata_yr}). This
showed that the mean weight-at-age is higher in the the B-season in the
area east of 170$^\circ$W compared to the A-season and B-season in the
area west of 170$^\circ$W.

## Parameters estimated within the assessment model



Fishing mortality is parameterized to be semi-separable with year and
age (selectivity) components. The age component is allowed to vary over
time; changes are allowed in each year. The mean value of the age
component is constrained to equal one and the last 5 age groups (ages
11--15) are specified to be equal. This latter specification feature is
intended to reduce the number of parameters while acknowledging that
pollock in this age-range are likely to exhibit similar life-history
characteristics (i.e., unlikely to change their relative availability to
the fishery with age). The annual components of fishing mortality result
in `r n<-thisyr-1963` `r n` parameters and the age-time selectivity
schedule forms a 10x`r paste0(n," matrix of ",10*n)` parameters bringing
the total fishing mortality parameters to `r n+n*10`. The rationale for
including time- varying selectivity has recently been supported as a
means to improve retrospective patterns (Szuwalski et al. 2017) and as
best practice (Martell and Stewart, 2013).

For surveys and indices, the treatment of the catchability coefficient,
and interactions with age-specific selectivity require consideration.
For the BTS index, selectivity-at-age is estimated with a logistic curve
in which year specific deviations in the parameters is allowed. Such
time-varying survey selectivity is estimated to account for changes in
the availability of pollock to the survey gear and is constrained by
pre-specified variance terms. Presently, these variance terms have been
set based on balancing input data-based variances and are somewhat
subjective. For the AT survey, which originally began in 1979 (the
current series including data down to 0.5 m from bottom begins in 1994),
optional parameters to allow for age and time-varying patterns exist but
for this assessment and other recent assessments, ATS selectivity is
constant over time. Overall, four catchability coefficients were
estimated: one each for the early fishery catch-per-unit effort (CPUE)
data (from Low and Ikeda, 1980), the VAST combined bottom trawl survey index,
the AT survey data, and the AVO data.
An uninformative prior distribution is used for all of the indices. The
selectivity parameters for the 2 main indices (BTS and ATS) total 135 (the CPUE and
AVO data mirror the fishery and AT survey selectivities, respectively).

Additional fishing mortality rates used for recommending harvest levels
are estimated conditionally on other outputs from the model. For
example, the values corresponding to the $F_{40\%}$ $F_{35\%}$ and
$F_{MSY}$ harvest rates are found by satisfying the constraint that,
given age-specific population parameters (e.g., selectivity, maturity,
mortality, weight-at-age), unique values exist that correspond to these
fishing mortality rates. The likelihood components that are used to fit
the model can be categorized as:

-   Total catch biomass (log-normal, $\sigma=0.05$)
-   Log-normal indices of pollock biomass; bottom trawl surveys assume
    annual estimates of sampling error, as represented in Fig.
    \ref{fig:bts_biom} along with the covariance matrices (for the
    density-dependent and VAST index series); for the AT index the
    annual errors were specified to have a mean CV of 0.20; while for
    the AVO data, a value relative to the AT index was estimated and
    scaled to have a mean CV of 0.3).
-   Fishery and survey proportions-at-age estimates (multinomial with
    effective sample sizes presented Table \ref{tab:input_n}).
-   Age 1 index from the AT survey (CV set equal to 30% as in prior
    assessments).\
-   Selectivity constraints: penalties/priors on age-age variability,
    time changes, and decreasing (with age) patterns.
-   Stock-recruitment: penalties/priors involved with fitting a
    stochastic stock-recruitment relationship within the integrated
    model.
-   "Fixed effects" terms accounting for cohort and year sources of
    variability in fishery mean weights-at-age estimated based on
    available data from 1991-`r lastyr` from the fishery (and
    1982-`r thisyr` for the bottom-trawl survey data) and externally
    estimated variance terms as described in Appendix 1A of Ianelli et
    al. (2016; see Fig. \ref{fig:fish_wtage_data_pred}).

Work evaluating temperature and predation-dependent effects on the stock-
recruitment estimates continues (Spencer et al. 2016). This approach modified
the estimation of the stock-recruitment relationship by including the effect of
temperature and predation mortality. A relationship between recruitment
residuals and temperature was noted(similar to that found in Mueter et al.,
2011 and subsequently noted in Thorson et al., 2020a) and lower pollock
recruitment during warmer conditions might be expected. Similar results
relating summer temperature conditions to subsequent pollock recruitment for
recent years were also found by Yasumiishi et al. (2015) where research
suggests that summer warmth is associated with earlier diapause of copepods
(Thorson et al., 2020b), such that a fall (but not spring) survey of copepod
densities is also associated with cold conditions and elevated recruitment
(Eisner et al., 2020).
