
# Fishery

## Description of the directed fishery

Historically, EBS pollock catches were low until directed foreign
fisheries began in 1964. Catches increased rapidly during the late 1960s
and reached a peak in 1970--75 when they ranged from 1.3 to 1.9 million
t annually. Following the peak catch in 1972, bilateral agreements with
Japan and the USSR resulted in reductions. During a 10-year period,
catches by foreign vessels operating in the "Donut Hole" region of the
Aleutian Basin were substantial totaling nearly 7 million t (Table
\ref{tab:catch}). A fishing moratorium for this area was enacted in 1993
and only trace amounts of pollock have been harvested from the Aleutian
Basin region since then. Since the late 1970s, the average EBS pollock
catch has been about 1.2 million t, ranging from 0.810 million t in 2009
to nearly 1.5 million t during 2002--2006 (Table \ref{tab:catch}).
United States vessels began fishing for pollock in 1980 and by 1988 the
fishery became fully domestic. The current observer program for the
domestic fishery formally began in 1991 and prior to that, observers
were deployed aboard the foreign and joint-venture operations since the
late 1970s. From the period 1991 to 2011 about 80% of the catch was
observed at sea or during dockside offloading. Since 2011, regulations
require that all vessels participating in the pollock fishery carry at
least one observer so nearly 100% of the pollock fishing operations are
monitored by scientifically trained observers. Historical catch
estimates used in the assessment, along with management measures (i.e.,
OFLs, ABCs and TACs) are shown in Table \ref{tab:abc_tac}.

### Catch patterns

The "A-season" for directed EBS pollock fishing opens on January 20th
and fishing typically extends into early-mid April. During this season
the fishery targets pre-spawning pollock and produces pollock roe that,
under optimal conditions, can comprise over 4% of the catch in weight.
The summer, or "B-season" presently opens on June 10th and fishing
extends through noon on November 1st. The A-season fishery concentrates
primarily north and west of Unimak Island depending on ice conditions
and fish distribution. There has also been effort along the 100m depth
contour (and deeper) between Unimak Island and the Pribilof Islands. The
general pattern by season (and area) has varied over time with recent
B-season catches occurring in the southeast portion of the shelf (east
of 170$^\circ$W longitude; Fig. \ref{fig:catch}). Since 2011,
regulations and industry-based measures to reduce Chinook salmon bycatch
have affected the spatial distribution of the fishery and to some
degree, the way individual vessel operators fish (Stram and Ianelli,
2014). In 2020, the fishing fleet encountered higher than normal bycatch
of herring and this has further constrained the fishing grounds due to
area closures. Additionally, sablefish appear to be highly abundant in
the region and have comprised a significant proportion of the incidental
catches in the pollock fishery (proportionally still less than 1% of the
total landings). Comparing encounters of bycatch relative to the effort
(total duration of all tows) the pollock fleet had a relatively flat
trend in the Chinook salmon bycatch while sablefish and herring was down
from the relatively high levels last year (Fig. \ref{fig:fsh_psc_cpue}).

The catch estimates by sex for the seasons indicate that over time, the
number of males and females has been fairly equal but in the period
2017-2020 the A-season catch of females has been slightly higher and
conversely, in the B-season there has been a slightly higher number of
males taken (Fig. \ref{fig:catch_sex}). This figure is updated through 2021
and shows the high numbers of fish taken in that year because they were 
smaller than average. 
The 2022 A-season fishery
spatial pattern had a higher concentrations of fishing near
Unimak and east compared to 2020 and 2021 (Fig. \ref{fig:catch_distn_a}). 
The amount of fishing near the Pribilof Islands was much lower than 
commonly observed in 2022. The 2022 A-season nominal catch
rates were lower than the 2020 peak (for the fleet in aggregate) (Fig.
\ref{fig:fsh_cpue}). Beginning in 2017, due to a regulatory change, up
to 45% of the TAC could be taken in the A-season (previously only 40% of
the TAC could be taken). This conservation measure was made to allow
greater flexibility to avoid Chinook salmon in the B-season. The pollock fleet 
as a whole continues to take advantage of this 
flexibility (Fig. \ref{fig:prop_a_season}). However, this figure
indicates that in 2022, the proportion of catch in February increased over the
2021 pattern and this was consistent in subsequent months as well. This
suggests that fishing conditions were improved.
Pollock roe is an important product coming from the winter fishery. The amount
produced in the 2022 A-season was the lowest since 2013 and 
continued the big drop from the previous year (Fig. \ref{fig:roe}).

The summer-fall fishing conditions for 2022 improved considerably over
2021 and was about average on nominal catch rates (Fig.
\ref{fig:fsh_cpue}). The number of hours the fleet required to catch the
same tonnage of pollock was also improved relative to 2020. In the
B-season catches in the northwestern area dropped relative to the
previous two years (Fig. \ref{fig:catch_distn_b}). In addition, we
present an approach first shown in 2019 to evaluate how concentrated the
fleet was on average. We called this a measure of fleet dispersion: the
relative distance or spread of the fishery in space. Briefly, the
calculation computes for a given day, the distance between all trawl
tows (within and across boats). These distances are then averaged for
year and season. Updated to this year, results indicated that in both
seasons the fleet was less dispersed than last year suggesting that
fishing was fairly concentrated without a need to fish in more places
(Fig \ref{fig:fleet_dispersal}).

We continued to investigate the tow specific mean weight of fish. 
These provide a direct mean somatic mass (pollock body
weight) for pollock within a tow. The data arise from the sampled
total weight (e.g., of several baskets of pollock) divided by the
enumerated number of fish in that sample. Such records exist for each
tow. Summing these by extrapolated weight of the pollock catch within
that tow, and binning by weight increments (here by 50 gram intervals),
allows us to obtain some additional fine-scale information on the size
trends in the pollock fishery. The annual patterns of these data show
that overall, the B-season of 2020 was different with the small mode of
fish persisting into the 2021 B-season (Fig. \ref{fig:fsh_wt_freq}).
Compiling the data by week we show that the fish size was consistent
the growth of the 2018 year class during this B-season (Fig. \ref{fig:fsh_wt_freq_week}).

The catch of EBS pollock has averaged 1.26 million t in the period since
1979. The lowest catches occurred in 2009 and 2010 when the limits were
set to 0.81 million t due to stock declines (Table \ref{tab:abc_tac}).
The recent 5-year average (2018-2022) catch has been 1.326 million t.
Pollock catches that are retained or discarded (based on NMFS observer
estimates) in the Eastern Bering Sea and Aleutian Islands for
1991--`r thisyr` are shown in Table \ref{tab:catch_disc}. Since 1991,
estimates of discarded pollock have ranged from a high of 9.6% of total
pollock catch in 1991 to recent lows of around 0.6% to 1.1%. These low values
reflect the implementation of the NMFS' Improved Retention /Improved
Utilization program. Prior to the implementation of the American
Fisheries Act (AFA) in 1999, higher discards may have occurred under the
"race for fish" and pollock marketable sizes were caught incidentally.
Since implementation of the AFA, the vessel operators have more time to
pursue optimal sizes of pollock for market since the quota is allocated
to vessels (via cooperative arrangements). In addition, several vessels
have made gear modifications to avoid retention of smaller pollock. In
all cases, the magnitude of discards counts as part of the total catch
for management (to ensure the TAC is not exceeded) and within the
assessment. Bycatch of other non-target, target, and prohibited species
is presented in the section titled Ecosystem Considerations below. In
that section it is noted that the bycatch of pollock in other target
fisheries is more than double the bycatch of other target species (e.g.,
Pacific cod) in the pollock fishery.

### Bycatch and Discards


## Management measures

The EBS pollock stock is managed by NMFS regulations that provide limits
on seasonal catch. The NMFS observer program data provide near real-time
statistics during the season and vessels operate within well-defined
limits. In most years, the TACs have been set well below the ABC value
and catches have stayed within these constraints (Table
\ref{tab:abc_tac}). Allocations of the TAC split first with 10% to
western Alaska communities as part of the Community Development Quota
(CDQ) program and the remainder between at-sea processors and
shore-based sectors. For a characterization of the CDQ program see
Haynie (2014). Seung and Ianelli (2016) combined a fish population
dynamics model with an economic model to evaluate regional impacts.

Due to concerns that groundfish fisheries may impact the rebuilding of
the Steller sea lion population, a number of management measures have
been implemented over the years. Some measures were designed to reduce
the possibility of competitive interactions between fisheries and
Steller sea lions. For the pollock fisheries, seasonal fishery catch and
pollock biomass distributions (from surveys) indicated that the apparent
disproportionately high seasonal harvest rates within Steller sea lion
critical habitat could lead to reduced sea lion prey densities.
Consequently, management measures redistributed the fishery both
temporally and spatially according to pollock biomass distributions.
This was intended to disperse fishing so that localized harvest rates
were more consistent with estimated annual exploitation rates. The
measures include establishing: 1) pollock fishery exclusion zones around
sea lion rookery or haulout sites; 2) phased-in reductions in the
seasonal proportions of TAC that can be taken from critical habitat; and
3) additional seasonal TAC releases to disperse the fishery in time.

Prior to adoption of the above management measures, the pollock fishery
occurred throughout each of the three major NMFS management regions of
the North Pacific Ocean: the Aleutian Islands (1,001,780 km$^2$ inside
the EEZ), the Eastern Bering Sea (968,600 km$^2$), and the Gulf of
Alaska (1,156,100 km$^2$). The marine portion of Steller sea lion
critical habitat in Alaska west of 150$^{\circ}$W encompasses 386,770
km$^2$ of ocean surface, or 12% of the fishery management regions.

From 1995--1999 84,100 km$^2$, or 22% of the Steller sea lion critical
habitat was closed to the pollock fishery. Most of this closure
consisted of the 10 and 20 nm radius all-trawl fishery exclusion zones
around sea lion rookeries (48,920 km$^2$, or 13% of critical habitat).
The remainder was largely management area 518 (35,180 km$^2$, or 9% of
critical habitat) that was closed pursuant to an international agreement
to protect spawning stocks of central Bering Sea pollock. In 1999, an
additional 83,080 km$^2$ (21%) of critical habitat in the Aleutian
Islands was closed to pollock fishing along with 43,170 km$^2$ (11%)
around sea lion haulouts in the GOA and Eastern Bering Sea. In 1998,
over 22,000 t of pollock were caught in the Aleutian Island region, with
over 17,000 t taken within critical habitat region. Between 1999 and
2004 a directed fishery for pollock was prohibited in this region.
Subsequently, 210,350 km$^2$ (54%) of critical habitat in the Aleutian
Islands was closed to the pollock fishery. In 2000 the remaining
phased-in reductions in the proportions of seasonal TAC that could be
caught within the BSAI Steller sea lion Conservation Area (SCA) were
implemented.

On the EBS shelf, an estimate (based on observer at-sea data) of the
proportion of pollock caught in the SCA has averaged about 44% annually.
During the A-season, the average is also about 44%. Nonetheless, the
proportion of pollock caught within the SCA varies considerably,
presumably due to temperature regimes and the relative population age
structure. The annual proportion of catch has ranged from an annual low
of 11% in 2010 to high of 60% in 1998--the 2019 annual value was 58% and
quite high again in the A-season (68%; Ianelli et al. 2020). The higher
values in recent years were likely due to good fishing conditions close
to the main port. The recent transition from at-sea observer sampling of
many catcher vessels to a combination of at-sea electronic monitoring
and shore-based observer sampling has resulted in a temporary hiatus in
to associate catches with specific areas. Work has progressed
to link the position information to offloads so that haul 
records could be used to evaluate fishing patterns.

The AFA reduced the capacity of the catcher/processor fleet and
permitted the formation of cooperatives in each industry sector by the
year 2000. Because of some of its provisions, the AFA gave the industry
the ability to respond efficiently to changes mandated for sea lion
conservation and salmon bycatch measures. Without such a catch-share
program, these additional measures would likely have been less effective
and less economical (Strong and Criddle 2014).

An additional strategy to minimize potential adverse effects on sea lion
populations is to disperse the fishery throughout more of the pollock
range on the Eastern Bering Sea shelf. While the distribution of fishing
during the A-season is limited due to ice and weather conditions, there
appears to be some dispersion to the northwest area (Fig.
\ref{fig:catch_distn_a}).

The majority (about 56%) of Chinook salmon caught as bycatch in the
pollock fishery originate from western Alaskan rivers. This was updated 
at the June 2022 Council meeting and is activities are monitored and reported
closely at the Council ([at this website](https://www.npfmc.org/fisheries-issues/bycatch/salmon-bycatch/ 
).
In summary, Chinook salmon bycatch management measures went into effect in 2011
which imposed revised prohibited species catch (PSC) limits. These limits,
when reached, close the fishery by sector and season (Amendment 91 to
the BSAI Groundfish Fishery Management Plan (FMP) resulting from the
NPFMC's 2009 action). Previously, all measures for salmon bycatch
imposed seasonal area closures when PSC levels reached the limit
(fishing could continue outside of the closed areas). The current
program imposes a dual cap system by fishing sector and season. A goal
of this system was to maintain incentives to avoid bycatch at a broad
range of relative salmon abundance (and encounter rates). Participants
are also required to take part in an incentive program agreement (IPA).
These IPAs are approved and reviewed annually by NMFS to ensure
individual vessel accountability. The fishery has been operating under
rules to implement this program since January 2011.

Further measures to reduce salmon bycatch in the pollock fishery were
developed and the Council took action on Amendment 110 to the BSAI
Groundfish FMP in April 2015. These additional measures were designed to
add protection for Chinook salmon by imposing more restrictive PSC
limits in times of low western Alaskan Chinook salmon abundance. This
included provisions within the IPAs that reduce fishing in months of
higher bycatch encounters and mandate the use of salmon excluders in
trawl nets. These provisions were also included to provide more flexible
management measures for chum salmon bycatch within the IPAs rather than
through regulatory provisions implemented by Amendment 84 to the FMP.
The new measure also included additional seasonal flexibility in pollock
fishing so that more pollock (proportionally) could be caught during
seasons when salmon bycatch rates were low. Specifically, an additional
5% of the pollock can be caught in the A-season (effectively changing
the seasonal allocation from 40% to 45% (as noted above in the
discussion assosciated with Fig. \ref{fig:prop_a_season}). These
measures are all part of Amendment 110 and a summary of this and other
key management measures is provided in Table \ref{tab:mgt}.

There are three time/area closures in regulation to minimize herring PSC
impacts: *Summer Herring Savings Area 1* an area south of 57$^\circ$N
latitude and between 162$^\circ$W and 164$^\circ$W longitude from June
15 through July 1st. *Summer Herring Savings Area 2* an area south of
56$^\circ$ 30' N latitude and between 164$^\circ$W and 167$^\circ$W
longitude from July 1 through August 15. *Winter Herring Savings Area*
an area between 58$^\circ$ and 60$^\circ$N latitude and between
172$^\circ$W and 175$^\circ$W longitude from September 1st through March
1st of the next fishing year.
